#ifndef CONFIG_H_
#define CONFIG_H_

// SERIAL SETTINGS
#define SERIALX Serial
#define BAUD 9600

// ROBOT ARM LENGTH
#define LOW_SHANK_LENGTH 180.0
#define HIGH_SHANK_LENGTH 180.0

#define END_EFFECTOR_OFFSET 0.0 // LENGTH FROM UPPER SHANK BEARING TO MIDPOINT OF END EFFECTOR IN MM. Not 54

// SCARA SETTINGS
#define L1 153.0 // shank1 length
#define L2 161.0 // shank2 length + gripperoffset
#define LEAD 8.0
#define GRIPPERFLOATHEIGHT 0.0 // mm, was 20.0

// INITIAL INTERPOLATION SETTINGS
#define INITIAL_X (L1 + L2) // CARTESIAN COORDINATE X
#define INITIAL_Y 0.0       // CARTESIAN COORDINATE Y
#define INITIAL_Z Z_MAX     // CARTESIAN COORDINATE Z

// STEPPER SETTINGS:
#define INVERSE_X_STEPPER true // true IF STEPPER MOVES OTHER WAY.
#define INVERSE_Y_STEPPER true // true IF STEPPER MOVES OTHER WAY.
#define INVERSE_Z_STEPPER true // true IF STEPPER MOVES OTHER WAY

// GEAR RATIO SETTINGS
#define MOTOR_GEAR_TEETH 9.0 // 20.0 FOR 20SFFACTORY BELT VERSION   9.0 FOR FTOBLER GEAR VERSION
#define MAIN_GEAR_TEETH 32.0 // 90.0 FOR 20SFFACTORY BELT VERSION   32.0 FOR FTOBLER GEAR VERSION

// SERVO GRIPPER SETTINGS
#define SERVO_GRIP_DEGREE 0.0
#define SERVO_UNGRIP_DEGREE 45.0

// COMMAND QUEUE SETTINGS
#define QUEUE_SIZE 15

// LOG SETTINGS
#define LOG_LEVEL 2
// 0: ERROR
// 1: INFO
// 2: DEBUG

// MOVE LIMIT PARAMETERS
#define Z_MIN -140.0                    // MINIMUM Z HEIGHT OF TOOLHEAD TOUCHING GROUND
#define Z_MAX (LOW_SHANK_LENGTH + 30.0) // SHANK_LENGTH ADDING ARBITUARY NUMBER FOR Z_MAX
#endif
